# Site settings
title: MOOG Media | A Concious Media Company
email: nauras@moogmedia.ca
description: We are a collective of professional artists and innovators that engage in new-age video storytelling
baseurl: ""
url: "www.moogmedia.ca"
github_username:  timelytree
include: ["_pages", "_projects"]
permalink: /:title

collections:
  category:
    output: true

# Build settings
markdown: kramdown

sass:
  sass_dir: _scss
